// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/cloudcampers-vibes/CoastalAgency.tsx": () => import("../components/mockups/cloudcampers-vibes/CoastalAgency.tsx"),
  "./components/mockups/cloudcampers-vibes/DigitalFrontier.tsx": () => import("../components/mockups/cloudcampers-vibes/DigitalFrontier.tsx"),
  "./components/mockups/cloudcampers-vibes/ExecutiveSuite.tsx": () => import("../components/mockups/cloudcampers-vibes/ExecutiveSuite.tsx"),
  "./components/mockups/cloudcampers-vibes/PrecisionMachine.tsx": () => import("../components/mockups/cloudcampers-vibes/PrecisionMachine.tsx"),
  "./components/mockups/cloudcampers-vibes/SoftAuthority.tsx": () => import("../components/mockups/cloudcampers-vibes/SoftAuthority.tsx"),
  "./components/mockups/cloudcampers-vibes/TrustedAdvisor.tsx": () => import("../components/mockups/cloudcampers-vibes/TrustedAdvisor.tsx")
};
